name: Build packages
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  static:
    name: Static
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install --production
      - name: Build
        run:  build/tar 1
      - name: Upload github artifact
        uses: actions/upload-artifact@v2
        with:
          path: '*.tar.gz'
          name: tar

  deb:
    name: Deb
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['ubuntu:focal', 'ubuntu:bionic', 'debian:buster', 'debian:stretch', 'debian:bullseye' ]
      fail-fast: false
    container:
      image: ${{ matrix.image }}
    steps:
      - run: apt-get update

      - name: Install dependencies
        run: env DEBIAN_FRONTEND=noninteractive apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian build-essential gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev zlib1g-dev curl jq

      - name: Install Crystal
        run: curl -fsSL https://crystal-lang.org/install.sh | bash -s -- --version=1.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build deb package
        run: build/deb

      - name: Test start
        run: bin/amqproxy --version
